---
name: 'build-2-6'
env: 
  folder: 2-virtual-wan/6-secure-virtual-wan-dual-hub
on:
  workflow_dispatch:    

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env: 
      ARM_CLIENT_ID: ${{secrets.TF_CliendId}}
      ARM_CLIENT_SECRET: ${{secrets.TF_clientSecret}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_subscriptionId}}
      ARM_TENANT_ID: ${{secrets.TF_tenantId}}
      GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
    defaults:
      run:
        shell: bash
        working-directory: ./${{env.folder}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      id: init
      run: terraform init
    #- name: Terraform Plan
    #  run: terraform plan
    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -parallelism 50
    #- name: send tele msg
    #  if: always()
    #  uses: appleboy/telegram-action@master
    #  with: 
    #    to: ${{ secrets.telegram_to}}
    #    token: ${{ secrets.telegram_token}}
    #    message: |
    #      ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
